### ISSUE TITLE
MYSQL_PORT is required while using MYSQL_HOST

### ISSUE THREAD

**Issue by CombatCode** [fradelg/docker-mysql-cron-backup#106]
When someone only defines the MYSQL_HOST container, it doesn't start. You need to define MYSQL_PORT, even if the port is the default port for MySQL.

**Comment by fradelg** [comment]
Hi,

Using the docker-compose.yaml un the root of the repository I am not able to reproduce the issue. Can you provide a reproducible example?

**Comment by nitic** [comment]
MYSQL_PORT is 'expose'


```
version: '3'

services:
  db:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
    expose:
      - '3306'
    ports:
      - '13306:3306'
    volumes:
      - 'data:/bitnami/mariadb'

  backup:
    image: 'fradelg/mysql-cron-backup'
    container_name: mariadb-backup
    environment:
      - MYSQL_HOST=mariadb-slave
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=demo
      - INIT_BACKUP=1
      - CRON_SCHEDULE=0 19 * * *
      - MAX_BACKUPS=7
      - GZIP_LEVEL=9
      - TZ=Asia/Bangkok
    volumes:
      - './backup:/backup'
    depends_on:
      - db

volumes:
  data:
    driver: local
```
