### ISSUE TITLE
V1.13.1 not working with mariadb:10.1

### ISSUE THREAD

**Issue by gioscarda** [fradelg/docker-mysql-cron-backup#126]
With this example docker compose config:
```
db:
    restart: unless-stopped
    environment:
      ...
    build:
      dockerfile_inline: |
        FROM mariadb:10.1

mysql-cron-backup-hourly:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    volumes:
      - ./backup/hourly:/backup:Z
    environment:
      MYSQLDUMP_OPTS: --no-tablespaces
      MYSQL_HOST: db
      MYSQL_USER: {MYSQL_USER}
      MYSQL_PASS: {MYSQL_PASS}
      GZIP_LEVEL: 9
      CRON_TIME: "@hourly"
      MAX_BACKUPS: 24
      INIT_BACKUP: 1
    restart: unless-stopped
```
We retrieve the following error message in docker logs:

_mysqldump: Couldn't execute 'select column_name, extra, generation_expression, data_type from information_schema.columns 
where table_schema=database() and table_name='<my-table>'': Unknown column 'generation_expression' in 'field list' (1054)_

Downgrading to `fradelg/mysql-cron-backup:1.13.0` it works fine.

Further info at https://stackoverflow.com/questions/75662086/suddenly-cannot-dump-remote-database-unknown-column-generation-expression-in (see comment by `0xC0DEGURU`).
