### ISSUE TITLE
ERROR 1046 (3D000) at line 22: No database selected

### ISSUE THREAD

**Issue by theniwo** [fradelg/docker-mysql-cron-backup#35]
When running 
`docker container exec nextcloud_db_backup_1 /restore.sh /backup/latest.nextcloud.sql.gz`

I get that error.
```
=> Restore database from /backup/latest.nextcloud.sql.gz
ERROR 1046 (3D000) at line 22: No database selected
=> Restore failed
```
Part of my compose file:
```
  db_backup:
    image: fradelg/mysql-cron-backup
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./db.env
      - ./global.env
    environment:
      - MYSQL_DB=nextcloud
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=nextcloud
      - MAX_BACKUPS=15
      - INIT_BACKUP=1
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
      # Make it small
      - GZIP_LEVEL=9
    volumes:
      - db_backup:/backup
```
