### ISSUE TITLE
ERROR: for project-mysql  Cannot create container for service mysql: mkdir /home/chiqui3d/project/data/backup/latest.project_docker.sql.gz: file exists

### ISSUE THREAD

**Issue by chiqui3d** [fradelg/docker-mysql-cron-backup#39]
Hello, 

Do you know why I'm getting this error when I try to make a `docker-compose up -d --build`

`ERROR: for project-mysql  Cannot create container for service mysql: mkdir /home/chiqui3d/project/data/backup/latest.project_docker.sql.gz: file exists`

This is the configuration of docker-compose.yml

```
volumes:
  dbdata:
  appdata:

services:
  backup:
    container_name: ${PROJECT_NAME}-backup
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql
    volumes:
      - ./data/backup:/backup
    environment:
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MAX_BACKUPS=15
      - INIT_BACKUP=1
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
    restart: unless-stopped
    networks:
      - db
  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
        - DOCKER_ENV=${DOCKER_ENV}
    restart: always
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./data/backup/latest.${MYSQL_DATABASE}.sql.gz:/docker-entrypoint-initdb.d/database.sql.gz
    networks:
      - db
```
