### ISSUE TITLE
Arbitrary user for container

### ISSUE THREAD

**Issue by steakhutzeee** [fradelg/docker-mysql-cron-backup#46]
Hi,

have a quick question, can this container be run as an user different from root?

Thanks!

**Comment by fradelg** [comment]
Hi,

I haven't tried but technically you can as long as that user has access to the mounted volume where the backups are stored. You might have some issues with the rights of the executable scripts copied into the docker image but the best way to know is trying it.

**Comment by steakhutzeee** [comment]
> 
> 
> Hi,
> 
> I haven't tried but technically you can as long as that user has access to the mounted volume where the backups are stored. You might have some issues with the rights of the executable scripts copied into the docker image but the best way to know is trying it.

These are the logs:

today at 00:45:11  2021/05/01 00:45:11 Waiting for: tcp://bookstack_db:3306
today at 00:45:11  2021/05/01 00:45:11 Connected to tcp://bookstack_db:3306
today at 00:45:11  touch: /mysql_backup.log: Permission denied
today at 00:45:11  tail: can't open '/mysql_backup.log': No such file or directory
today at 00:45:11  => Create a backup on the startup
today at 00:45:11  => Backup started at 2021-05-01 00:45:11
today at 00:45:11  ==> Dumping database: bookstackapp
today at 00:45:11  ==> Creating symlink to latest backup: 202105010045.bookstackapp.sql.gz
today at 00:45:11  /
today at 00:45:12  => Backup process finished at 2021-05-01 00:45:12
today at 00:45:12  /run.sh: line 18: /crontab.conf: Permission denied
today at 00:45:12  crontab: must be suid to work properly
today at 00:45:12  => Running cron task manage

**Comment by steakhutzeee** [comment]
Hi,

any hint? :)

**Comment by fradelg** [comment]
Can you paste tour docker cli line or docker-compose.yml file to reproduce the issue?

**Comment by steakhutzeee** [comment]
> 
> 
> Can you paste your docker cli line or docker-compose.yml file to reproduce the issue?

Sure:

  ```
mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    container_name: bookstack_db_bak
    depends_on:
        - bookstack_db
    user: 1000:100
    volumes:
       - /srv/dev-disk-by-label-HC2/AppData/bookstack_db_bak/backup:/backup
    environment:
      - MYSQL_HOST=bookstack_db
      - MYSQL_USER=xxx
      - MYSQL_PASS=xxx
      - MAX_BACKUPS=7
      - INIT_BACKUP=1
      - CRON_TIME=0 0 * * * # Every day at 00
      - GZIP_LEVEL=9 # High compression level
      - TZ=Europe/Rome
      - MYSQLDUMP_OPTS=--skip-lock-tables --single-transaction --quick
    restart: unless-stopped  
```
