### ISSUE TITLE
Add option to RUN_ONCE in order to use this image for Kubernetes Cronjobs

### ISSUE THREAD

**Issue by Skaronator** [fradelg/docker-mysql-cron-backup#65]
Hi,

Would it be possible to add a `RUN_ONCE` option to the image which means that it'll do a backup on startup (like `INIT_BACKUP`) but after that will exit/stop the container?

I'd like to continue using the image but with a Kubernetes Cronjob. So, the Container orchestrator takes care of scheduling the container.

**Comment by fradelg** [comment]
Hi,

Indeed, Kubernetes is already supported. You only have to change the command. 

A CronJob like this may work (WARNING: I haven't tested it):

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 3 * * sun"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: fradelg/mysql-cron-backup:<my-tag>
            imagePullPolicy: IfNotPresent
            command:
            - /backup.sh
          restartPolicy: OnFailure
````
